// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtfL92CxPBF3C0zZQm0v8U1Pv4_KYSa88',
    appId: '1:1052880675814:web:76c2f5f97d614d1ad62c27',
    messagingSenderId: '1052880675814',
    projectId: 'travel-plan-7e416',
    authDomain: 'travel-plan-7e416.firebaseapp.com',
    storageBucket: 'travel-plan-7e416.firebasestorage.app',
    measurementId: 'G-X55F4WZL1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD68_nHC5Ff3Uxa-JJJUTTt5YNsT9b3HQs',
    appId: '1:1052880675814:android:25373b0b2c9175e9d62c27',
    messagingSenderId: '1052880675814',
    projectId: 'travel-plan-7e416',
    storageBucket: 'travel-plan-7e416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Qzv0EiZLVDvNrCmTID8941b7RZ6Frxc',
    appId: '1:1052880675814:ios:a18659079c02f101d62c27',
    messagingSenderId: '1052880675814',
    projectId: 'travel-plan-7e416',
    storageBucket: 'travel-plan-7e416.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Qzv0EiZLVDvNrCmTID8941b7RZ6Frxc',
    appId: '1:1052880675814:ios:a18659079c02f101d62c27',
    messagingSenderId: '1052880675814',
    projectId: 'travel-plan-7e416',
    storageBucket: 'travel-plan-7e416.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtfL92CxPBF3C0zZQm0v8U1Pv4_KYSa88',
    appId: '1:1052880675814:web:2ab2812ec0dda10bd62c27',
    messagingSenderId: '1052880675814',
    projectId: 'travel-plan-7e416',
    authDomain: 'travel-plan-7e416.firebaseapp.com',
    storageBucket: 'travel-plan-7e416.firebasestorage.app',
    measurementId: 'G-NJS6FDDKRM',
  );
}
