// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoXdJd1tgtlMlT22tZsKNKMAUeuV4D3g',
    appId: '1:774572899941:web:436a3e5c1fabe5053c908c',
    messagingSenderId: '774572899941',
    projectId: 'hackyoyo-28ad2',
    authDomain: 'hackyoyo-28ad2.firebaseapp.com',
    storageBucket: 'hackyoyo-28ad2.firebasestorage.app',
    measurementId: 'G-19D8Y6BDRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUIQ5iEyVLV9I1AOxvQXOpLKO5zu2ee1A',
    appId: '1:774572899941:android:e941bdaab01a333a3c908c',
    messagingSenderId: '774572899941',
    projectId: 'hackyoyo-28ad2',
    storageBucket: 'hackyoyo-28ad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTpXfqKULGfdUJHwduAupyDPfQME6X2I',
    appId: '1:774572899941:ios:1d5588173e33f73a3c908c',
    messagingSenderId: '774572899941',
    projectId: 'hackyoyo-28ad2',
    storageBucket: 'hackyoyo-28ad2.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTpXfqKULGfdUJHwduAupyDPfQME6X2I',
    appId: '1:774572899941:ios:1d5588173e33f73a3c908c',
    messagingSenderId: '774572899941',
    projectId: 'hackyoyo-28ad2',
    storageBucket: 'hackyoyo-28ad2.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBoXdJd1tgtlMlT22tZsKNKMAUeuV4D3g',
    appId: '1:774572899941:web:daabb470febf16ed3c908c',
    messagingSenderId: '774572899941',
    projectId: 'hackyoyo-28ad2',
    authDomain: 'hackyoyo-28ad2.firebaseapp.com',
    storageBucket: 'hackyoyo-28ad2.firebasestorage.app',
    measurementId: 'G-ZE3343DKCX',
  );

}