// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-1YhS0ZaKYfYwKdZ_fDrTa9a1yDShRA',
    appId: '1:1088581851074:web:d9bb41ec8ed18ce909a85b',
    messagingSenderId: '1088581851074',
    projectId: 'travel-plan-caba3',
    authDomain: 'travel-plan-caba3.firebaseapp.com',
    storageBucket: 'travel-plan-caba3.firebasestorage.app',
    measurementId: 'G-M1D88NRVJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtw3VRkq3RUZvV2YiIbtRsnZihLIFMA30',
    appId: '1:1088581851074:android:ea187c5edbb37a4909a85b',
    messagingSenderId: '1088581851074',
    projectId: 'travel-plan-caba3',
    storageBucket: 'travel-plan-caba3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVW_M841a1I2u69yW1fgpdf_GCO1s8zQo',
    appId: '1:1088581851074:ios:fdf532feea7c0da009a85b',
    messagingSenderId: '1088581851074',
    projectId: 'travel-plan-caba3',
    storageBucket: 'travel-plan-caba3.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVW_M841a1I2u69yW1fgpdf_GCO1s8zQo',
    appId: '1:1088581851074:ios:fdf532feea7c0da009a85b',
    messagingSenderId: '1088581851074',
    projectId: 'travel-plan-caba3',
    storageBucket: 'travel-plan-caba3.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB-1YhS0ZaKYfYwKdZ_fDrTa9a1yDShRA',
    appId: '1:1088581851074:web:7f39c5b4948ee13f09a85b',
    messagingSenderId: '1088581851074',
    projectId: 'travel-plan-caba3',
    authDomain: 'travel-plan-caba3.firebaseapp.com',
    storageBucket: 'travel-plan-caba3.firebasestorage.app',
    measurementId: 'G-6SCXPRQV8V',
  );

}