import '../models/destination.dart';

class DestinationService {  // 熱門國內地點（日本）
  static List<Destination> getPopularDomesticDestinations() {
    return [
      Destination(
        id: 'sapporo',
        name: '札幌',
        country: '日本',
        prefecture: '北海道',
        type: 'domestic',
        imageUrl: 'https://api.allorigins.win/raw?url=https://www.visit-hokkaido.jp/lsc/upfile/course/0000/0011/11_1_l.jpg',
        isPopular: true,
        latitude: 43.0642,
        longitude: 141.3469,
      ),
      Destination(
        id: 'hakodate',
        name: '函館',
        country: '日本',
        prefecture: '北海道',
        type: 'domestic',
        imageUrl: 'https://api.allorigins.win/raw?url=https://www.hakobura.jp/assets/charms/mv-4-975f693bea7723dadc1b9c515c30b5c99798b2defd30e1f6c9cc1429e166f097.jpg',
        isPopular: true,
        latitude: 41.7687,
        longitude: 140.7290,
      ),
      Destination(
        id: 'tokyo',
        name: '東京',
        country: '日本',
        prefecture: '東京都',
        type: 'domestic',
        imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 35.6762,
        longitude: 139.6503,
      ),
      Destination(
        id: 'osaka',
        name: '大阪',
        country: '日本',
        prefecture: '大阪府',
        type: 'domestic',
        imageUrl: 'https://api.allorigins.win/raw?url=https://img.enjoy-osaka-kyoto-kobe.com/wp-content/uploads/2022/08/06173028/07_osakajyo.webp',
        isPopular: true,
        latitude: 34.6937,
        longitude: 135.5023,
      ),
      Destination(
        id: 'kyoto',
        name: '京都',
        country: '日本',
        prefecture: '京都府',
        type: 'domestic',
        imageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 35.0116,
        longitude: 135.7681,
      ),
      Destination(
        id: 'nara',
        name: '奈良',
        country: '日本',
        prefecture: '奈良縣',
        type: 'domestic',
        imageUrl: 'https://api.allorigins.win/raw?url=https://mimihan.tw/wp-content/uploads/20191129154109_16.jpg',
        isPopular: true,
        latitude: 34.6851,
        longitude: 135.8048,
      ),
      Destination(
        id: 'yokohama',
        name: '橫濱',
        country: '日本',
        prefecture: '神奈川縣',
        type: 'domestic',
        imageUrl: 'https://api.allorigins.win/raw?url=https://aumo-taiwan-images.s3.ap-northeast-1.amazonaws.com/production/wp-content/uploads/2023/01/30184750/pixta_79908180_M-1024x683.jpg',
        isPopular: true,
        latitude: 35.4437,
        longitude: 139.6380,
      ),
      Destination(
        id: 'hiroshima',
        name: '廣島',
        country: '日本',
        prefecture: '廣島縣',
        type: 'domestic',
        imageUrl: 'https://images.unsplash.com/photo-1588558351b5-a2a6e73b57fb?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 34.3853,
        longitude: 132.4553,
      ),
      Destination(
        id: 'fukuoka',
        name: '福岡',
        country: '日本',
        prefecture: '福岡縣',
        type: 'domestic',
        imageUrl: 'https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 33.5904,
        longitude: 130.4017,
      ),
      Destination(
        id: 'okinawa',
        name: '沖繩',
        country: '日本',
        prefecture: '沖繩縣',
        type: 'domestic',
        imageUrl: 'https://images.unsplash.com/photo-1564544966451-e023d6372ab4?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 26.2124,
        longitude: 127.6792,
      ),
      Destination(
        id: 'nagoya',
        name: '名古屋',
        country: '日本',
        prefecture: '愛知縣',
        type: 'domestic',
        imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 35.1815,
        longitude: 136.9066,
      ),
      Destination(
        id: 'kanazawa',
        name: '金澤',
        country: '日本',
        prefecture: '石川縣',
        type: 'domestic',
        imageUrl: 'https://images.unsplash.com/photo-1549048172-4b0e70ea8d10?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 36.5619,
        longitude: 136.6562,
      ),
    ];
  }

  // 熱門國外地點
  static List<Destination> getPopularInternationalDestinations() {
    return [
      Destination(
        id: 'paris',
        name: '巴黎',
        country: '法國',
        type: 'international',
        imageUrl: 'https://api.allorigins.win/raw?url=https://www.cometoparis.com/data/layout_image/20784_20770_1.800w_landscape_3-2_xl.jpg?ver=1738235518',
        isPopular: true,
        latitude: 48.8566,
        longitude: 2.3522,
      ),
      Destination(
        id: 'london',
        name: '倫敦',
        country: '英國',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 51.5074,
        longitude: -0.1278,
      ),
      Destination(
        id: 'rome',
        name: '羅馬',
        country: '義大利',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 41.9028,
        longitude: 12.4964,
      ),
      Destination(
        id: 'barcelona',
        name: '巴塞隆納',
        country: '西班牙',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 41.3851,
        longitude: 2.1734,
      ),
      Destination(
        id: 'amsterdam',
        name: '阿姆斯特丹',
        country: '荷蘭',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 52.3676,
        longitude: 4.9041,
      ),
      Destination(
        id: 'berlin',
        name: '柏林',
        country: '德國',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1560930950-5cc20e80d392?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 52.5200,
        longitude: 13.4050,
      ),
      Destination(
        id: 'vienna',
        name: '維也納',
        country: '奧地利',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1516550135131-fe3dcb0bedc7?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 48.2082,
        longitude: 16.3738,
      ),
      Destination(
        id: 'prague',
        name: '布拉格',
        country: '捷克',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 50.0755,
        longitude: 14.4378,
      ),
      Destination(
        id: 'seoul',
        name: '首爾',
        country: '韓國',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1599367815384-3c1c47b2c17f?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 37.5665,
        longitude: 126.9780,
      ),
      Destination(
        id: 'singapore',
        name: '新加坡',
        country: '新加坡',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 1.3521,
        longitude: 103.8198,
      ),
      Destination(
        id: 'hongkong',
        name: '香港',
        country: '中國',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 22.3193,
        longitude: 114.1694,
      ),
      Destination(
        id: 'taipei',
        name: '台北',
        country: '台灣',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1508584454580-6eb4f0fa17b8?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 25.0330,
        longitude: 121.5654,
      ),
      Destination(
        id: 'bangkok',
        name: '曼谷',
        country: '泰國',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 13.7563,
        longitude: 100.5018,
      ),
      Destination(
        id: 'sydney',
        name: '雪梨',
        country: '澳洲',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: -33.8688,
        longitude: 151.2093,
      ),
      Destination(
        id: 'newyork',
        name: '紐約',
        country: '美國',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 40.7128,
        longitude: -74.0060,
      ),
      Destination(
        id: 'losangeles',
        name: '洛杉磯',
        country: '美國',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1534281219520-bc2e1b0f26ea?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 34.0522,
        longitude: -118.2437,
      ),
      Destination(
        id: 'vancouver',
        name: '溫哥華',
        country: '加拿大',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 49.2827,
        longitude: -123.1207,
      ),
      Destination(
        id: 'toronto',
        name: '多倫多',
        country: '加拿大',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 43.6532,
        longitude: -79.3832,
      ),
      Destination(
        id: 'reykjavik',
        name: '雷克雅維克',
        country: '冰島',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 64.1466,
        longitude: -21.9426,
      ),
      Destination(
        id: 'dubai',
        name: '杜拜',
        country: '阿聯酋',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 25.2048,
        longitude: 55.2708,
      ),
      Destination(
        id: 'istanbul',
        name: '伊斯坦堡',
        country: '土耳其',
        type: 'international',
        imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=800&q=80',
        isPopular: true,
        latitude: 41.0082,
        longitude: 28.9784,
      ),
    ];
  }

  // 國外目的地（按國家分組）
  static Map<String, List<Destination>> getInternationalDestinations() {
    return {
      '美國': [
        Destination(
          id: 'newyork',
          name: '紐約',
          country: '美國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 40.7128,
          longitude: -74.0060,
        ),
        Destination(
          id: 'losangeles',
          name: '洛杉磯',
          country: '美國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1534281219520-bc2e1b0f26ea?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 34.0522,
          longitude: -118.2437,
        ),
        Destination(
          id: 'chicago',
          name: '芝加哥',
          country: '美國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 41.8781,
          longitude: -87.6298,
        ),
        Destination(
          id: 'sanfrancisco',
          name: '舊金山',
          country: '美國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1543914077-d1461c8cbf5a?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 37.7749,
          longitude: -122.4194,
        ),
      ],
      '法國': [
        Destination(
          id: 'paris',
          name: '巴黎',
          country: '法國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1502602898536-47ad22581b52?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 48.8566,
          longitude: 2.3522,
        ),
        Destination(
          id: 'nice',
          name: '尼斯',
          country: '法國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 43.7102,
          longitude: 7.2620,
        ),
        Destination(
          id: 'lyon',
          name: '里昂',
          country: '法國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 45.7640,
          longitude: 4.8357,
        ),
      ],
      '英國': [
        Destination(
          id: 'london',
          name: '倫敦',
          country: '英國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 51.5074,
          longitude: -0.1278,
        ),
        Destination(
          id: 'manchester',
          name: '曼徹斯特',
          country: '英國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1583484963846-ccea4bfa0d9f?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 53.4808,
          longitude: -2.2426,
        ),
        Destination(
          id: 'edinburgh',
          name: '愛丁堡',
          country: '英國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 55.9533,
          longitude: -3.1883,
        ),
      ],
      '韓國': [
        Destination(
          id: 'seoul',
          name: '首爾',
          country: '韓國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1599367815384-3c1c47b2c17f?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 37.5665,
          longitude: 126.9780,
        ),
        Destination(
          id: 'busan',
          name: '釜山',
          country: '韓國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 35.1796,
          longitude: 129.0756,
        ),
        Destination(
          id: 'jeju',
          name: '濟州',
          country: '韓國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 33.4996,
          longitude: 126.5312,
        ),
      ],
      '泰國': [
        Destination(
          id: 'bangkok',
          name: '曼谷',
          country: '泰國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 13.7563,
          longitude: 100.5018,
        ),
        Destination(
          id: 'phuket',
          name: '普吉島',
          country: '泰國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1586500036706-41963de24d8b?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 7.8804,
          longitude: 98.3923,
        ),
        Destination(
          id: 'chiangmai',
          name: '清邁',
          country: '泰國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 18.7883,
          longitude: 98.9853,
        ),
      ],
      '新加坡': [
        Destination(
          id: 'singapore',
          name: '新加坡',
          country: '新加坡',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 1.3521,
          longitude: 103.8198,
        ),
      ],
      '澳洲': [
        Destination(
          id: 'sydney',
          name: '雪梨',
          country: '澳洲',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: -33.8688,
          longitude: 151.2093,
        ),
        Destination(
          id: 'melbourne',
          name: '墨爾本',
          country: '澳洲',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1514395462725-fb4566210144?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: -37.8136,
          longitude: 144.9631,
        ),
        Destination(
          id: 'brisbane',
          name: '布里斯本',
          country: '澳洲',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1529108190281-9a4f620bc2d8?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: -27.4698,
          longitude: 153.0251,
        ),
      ],
      '加拿大': [
        Destination(
          id: 'vancouver',
          name: '溫哥華',
          country: '加拿大',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 49.2827,
          longitude: -123.1207,
        ),
        Destination(
          id: 'toronto',
          name: '多倫多',
          country: '加拿大',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 43.6532,
          longitude: -79.3832,
        ),
        Destination(
          id: 'montreal',
          name: '蒙特婁',
          country: '加拿大',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1553986909-ca8acf9b7ac8?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 45.5017,
          longitude: -73.5673,
        ),
      ],
      '義大利': [
        Destination(
          id: 'rome',
          name: '羅馬',
          country: '義大利',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 41.9028,
          longitude: 12.4964,
        ),
        Destination(
          id: 'milan',
          name: '米蘭',
          country: '義大利',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 45.4642,
          longitude: 9.1900,
        ),
        Destination(
          id: 'venice',
          name: '威尼斯',
          country: '義大利',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 45.4408,
          longitude: 12.3155,
        ),
      ],
      '西班牙': [
        Destination(
          id: 'barcelona',
          name: '巴塞隆納',
          country: '西班牙',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 41.3851,
          longitude: 2.1734,
        ),
        Destination(
          id: 'madrid',
          name: '馬德里',
          country: '西班牙',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 40.4168,
          longitude: -3.7038,
        ),
      ],
      '德國': [
        Destination(
          id: 'berlin',
          name: '柏林',
          country: '德國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1560930950-5cc20e80d392?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 52.5200,
          longitude: 13.4050,
        ),
        Destination(
          id: 'munich',
          name: '慕尼黑',
          country: '德國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1595846519845-68e298c2edd8?auto=format&fit=crop&w=800&q=80',
          isPopular: false,
          latitude: 48.1351,
          longitude: 11.5820,
        ),
      ],
      '荷蘭': [
        Destination(
          id: 'amsterdam',
          name: '阿姆斯特丹',
          country: '荷蘭',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 52.3676,
          longitude: 4.9041,
        ),
      ],
      '奧地利': [
        Destination(
          id: 'vienna',
          name: '維也納',
          country: '奧地利',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1516550135131-fe3dcb0bedc7?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 48.2082,
          longitude: 16.3738,
        ),
      ],
      '捷克': [
        Destination(
          id: 'prague',
          name: '布拉格',
          country: '捷克',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 50.0755,
          longitude: 14.4378,
        ),
      ],
      '中國': [
        Destination(
          id: 'hongkong',
          name: '香港',
          country: '中國',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 22.3193,
          longitude: 114.1694,
        ),
      ],
      '台灣': [
        Destination(
          id: 'taipei',
          name: '台北',
          country: '台灣',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1508584454580-6eb4f0fa17b8?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 25.0330,
          longitude: 121.5654,
        ),
      ],
      '阿聯酋': [
        Destination(
          id: 'dubai',
          name: '杜拜',
          country: '阿聯酋',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 25.2048,
          longitude: 55.2708,
        ),
      ],
      '土耳其': [
        Destination(
          id: 'istanbul',
          name: '伊斯坦堡',
          country: '土耳其',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 41.0082,
          longitude: 28.9784,
        ),
      ],
      '冰島': [
        Destination(
          id: 'reykjavik',
          name: '雷克雅維克',
          country: '冰島',
          type: 'international',
          imageUrl: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73aff?auto=format&fit=crop&w=800&q=80',
          isPopular: true,
          latitude: 64.1466,
          longitude: -21.9426,
        ),
      ],
    };
  }

  // 所有日本都道府縣和城市
  static Map<String, List<Destination>> getDomesticDestinations() {
    return {
      '北海道': [
        Destination(id: 'sapporo', name: '札幌', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 43.0642, longitude: 141.3469),
        Destination(id: 'hakodate', name: '函館', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 41.7687, longitude: 140.7290),
        Destination(id: 'asahikawa', name: '旭川', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 43.7711, longitude: 142.3649),
        Destination(id: 'kushiro', name: '釧路', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 42.9849, longitude: 144.3820),
        Destination(id: 'obihiro', name: '帶廣', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 42.9236, longitude: 143.2025),
        Destination(id: 'kitami', name: '北見', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 43.8048, longitude: 143.8966),
        Destination(id: 'otaru', name: '小樽', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 43.1907, longitude: 140.9947),
        Destination(id: 'muroran', name: '室蘭', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 42.3169, longitude: 140.9740),
        Destination(id: 'tomakomai', name: '苫小牧', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 42.6341, longitude: 141.6026),
        Destination(id: 'wakkanai', name: '稚內', country: '日本', prefecture: '北海道', type: 'domestic', latitude: 45.4095, longitude: 141.6739),
      ],
      '青森縣': [
        Destination(id: 'aomori', name: '青森', country: '日本', prefecture: '青森縣', type: 'domestic', latitude: 40.8244, longitude: 140.7400),
        Destination(id: 'hirosaki', name: '弘前', country: '日本', prefecture: '青森縣', type: 'domestic', latitude: 40.6039, longitude: 140.4639),
        Destination(id: 'hachinohe', name: '八戶', country: '日本', prefecture: '青森縣', type: 'domestic', latitude: 40.5156, longitude: 141.4889),
        Destination(id: 'goshogawara', name: '五所川原', country: '日本', prefecture: '青森縣', type: 'domestic', latitude: 40.8042, longitude: 140.4411),
        Destination(id: 'towada', name: '十和田', country: '日本', prefecture: '青森縣', type: 'domestic', latitude: 40.6167, longitude: 141.2069),
      ],
      '岩手縣': [
        Destination(id: 'morioka', name: '盛岡', country: '日本', prefecture: '岩手縣', type: 'domestic', latitude: 39.7036, longitude: 141.1527),
        Destination(id: 'ichinoseki', name: '一關', country: '日本', prefecture: '岩手縣', type: 'domestic', latitude: 38.9342, longitude: 141.1289),
        Destination(id: 'rikuzentakata', name: '陸前高田', country: '日本', prefecture: '岩手縣', type: 'domestic', latitude: 39.0139, longitude: 141.6306),
        Destination(id: 'hanamaki', name: '花卷', country: '日本', prefecture: '岩手縣', type: 'domestic', latitude: 39.3889, longitude: 141.1139),
        Destination(id: 'kitakami', name: '北上', country: '日本', prefecture: '岩手縣', type: 'domestic', latitude: 39.2864, longitude: 141.1139),
      ],
      '宮城縣': [
        Destination(id: 'sendai', name: '仙台', country: '日本', prefecture: '宮城縣', type: 'domestic', latitude: 38.2682, longitude: 140.8694),
        Destination(id: 'ishinomaki', name: '石卷', country: '日本', prefecture: '宮城縣', type: 'domestic', latitude: 38.4342, longitude: 141.3028),
        Destination(id: 'shiogama', name: '鹽竈', country: '日本', prefecture: '宮城縣', type: 'domestic', latitude: 38.3167, longitude: 141.0167),
        Destination(id: 'kesennuma', name: '氣仙沼', country: '日本', prefecture: '宮城縣', type: 'domestic', latitude: 38.9078, longitude: 141.5708),
        Destination(id: 'natori', name: '名取', country: '日本', prefecture: '宮城縣', type: 'domestic', latitude: 38.1722, longitude: 140.8917),
      ],
      '秋田縣': [
        Destination(id: 'akita', name: '秋田', country: '日本', prefecture: '秋田縣', type: 'domestic', latitude: 39.7186, longitude: 140.1024),
        Destination(id: 'yokote', name: '橫手', country: '日本', prefecture: '秋田縣', type: 'domestic', latitude: 39.3139, longitude: 140.5556),
        Destination(id: 'odate', name: '大館', country: '日本', prefecture: '秋田縣', type: 'domestic', latitude: 40.2722, longitude: 140.5639),
        Destination(id: 'noshiro', name: '能代', country: '日本', prefecture: '秋田縣', type: 'domestic', latitude: 40.2139, longitude: 140.0278),
        Destination(id: 'yuzawa', name: '湯澤', country: '日本', prefecture: '秋田縣', type: 'domestic', latitude: 39.1611, longitude: 140.4944),
      ],
      '山形縣': [
        Destination(id: 'yamagata', name: '山形', country: '日本', prefecture: '山形縣', type: 'domestic', latitude: 38.2404, longitude: 140.3633),
        Destination(id: 'yonezawa', name: '米澤', country: '日本', prefecture: '山形縣', type: 'domestic', latitude: 37.9222, longitude: 140.1167),
        Destination(id: 'tsuruoka', name: '鶴岡', country: '日本', prefecture: '山形縣', type: 'domestic', latitude: 38.7267, longitude: 139.8256),
        Destination(id: 'sakata', name: '酒田', country: '日本', prefecture: '山形縣', type: 'domestic', latitude: 38.9144, longitude: 139.8311),
        Destination(id: 'tendo', name: '天童', country: '日本', prefecture: '山形縣', type: 'domestic', latitude: 38.3622, longitude: 140.3778),
      ],
      '福島縣': [
        Destination(id: 'fukushima', name: '福島', country: '日本', prefecture: '福島縣', type: 'domestic', latitude: 37.7503, longitude: 140.4676),
        Destination(id: 'koriyama', name: '郡山', country: '日本', prefecture: '福島縣', type: 'domestic', latitude: 37.4000, longitude: 140.3833),
        Destination(id: 'iwaki', name: '磐城', country: '日本', prefecture: '福島縣', type: 'domestic', latitude: 37.0481, longitude: 140.8869),
        Destination(id: 'aizuwakamatsu', name: '會津若松', country: '日本', prefecture: '福島縣', type: 'domestic', latitude: 37.4944, longitude: 139.9306),
        Destination(id: 'shirakawa', name: '白河', country: '日本', prefecture: '福島縣', type: 'domestic', latitude: 37.1250, longitude: 140.2139),
      ],
      '茨城縣': [
        Destination(id: 'mito', name: '水戶', country: '日本', prefecture: '茨城縣', type: 'domestic', latitude: 36.3414, longitude: 140.4467),
        Destination(id: 'tsukuba', name: '筑波', country: '日本', prefecture: '茨城縣', type: 'domestic', latitude: 36.0839, longitude: 140.1000),
        Destination(id: 'hitachi', name: '日立', country: '日本', prefecture: '茨城縣', type: 'domestic', latitude: 36.5997, longitude: 140.6508),
        Destination(id: 'tsuchiura', name: '土浦', country: '日本', prefecture: '茨城縣', type: 'domestic', latitude: 36.0722, longitude: 140.2028),
        Destination(id: 'koga', name: '古河', country: '日本', prefecture: '茨城縣', type: 'domestic', latitude: 36.1833, longitude: 139.7000),
      ],
      '栃木縣': [
        Destination(id: 'utsunomiya', name: '宇都宮', country: '日本', prefecture: '栃木縣', type: 'domestic', latitude: 36.5658, longitude: 139.8836),
        Destination(id: 'nikko', name: '日光', country: '日本', prefecture: '栃木縣', type: 'domestic', latitude: 36.7581, longitude: 139.6989),
        Destination(id: 'ashikaga', name: '足利', country: '日本', prefecture: '栃木縣', type: 'domestic', latitude: 36.3361, longitude: 139.4497),
        Destination(id: 'oyama', name: '小山', country: '日本', prefecture: '栃木縣', type: 'domestic', latitude: 36.3139, longitude: 139.8000),
        Destination(id: 'kanuma', name: '鹿沼', country: '日本', prefecture: '栃木縣', type: 'domestic', latitude: 36.5667, longitude: 139.7472),
      ],
      '群馬縣': [
        Destination(id: 'maebashi', name: '前橋', country: '日本', prefecture: '群馬縣', type: 'domestic', latitude: 36.3911, longitude: 139.0608),
        Destination(id: 'takasaki', name: '高崎', country: '日本', prefecture: '群馬縣', type: 'domestic', latitude: 36.3225, longitude: 139.0133),
        Destination(id: 'kiryu', name: '桐生', country: '日本', prefecture: '群馬縣', type: 'domestic', latitude: 36.4081, longitude: 139.3331),
        Destination(id: 'isesaki', name: '伊勢崎', country: '日本', prefecture: '群馬縣', type: 'domestic', latitude: 36.3111, longitude: 139.1956),
        Destination(id: 'ota', name: '太田', country: '日本', prefecture: '群馬縣', type: 'domestic', latitude: 36.2931, longitude: 139.3744),
      ],
      '埼玉縣': [
        Destination(id: 'saitama', name: '埼玉', country: '日本', prefecture: '埼玉縣', type: 'domestic', latitude: 35.8617, longitude: 139.6455),
        Destination(id: 'kawagoe', name: '川越', country: '日本', prefecture: '埼玉縣', type: 'domestic', latitude: 35.9253, longitude: 139.4856),
        Destination(id: 'kawaguchi', name: '川口', country: '日本', prefecture: '埼玉縣', type: 'domestic', latitude: 35.8075, longitude: 139.7239),
        Destination(id: 'tokorozawa', name: '所澤', country: '日本', prefecture: '埼玉縣', type: 'domestic', latitude: 35.7994, longitude: 139.4689),
        Destination(id: 'kumagaya', name: '熊谷', country: '日本', prefecture: '埼玉縣', type: 'domestic', latitude: 36.1475, longitude: 139.3881),
      ],
      '千葉縣': [
        Destination(id: 'chiba', name: '千葉', country: '日本', prefecture: '千葉縣', type: 'domestic', latitude: 35.6074, longitude: 140.1065),
        Destination(id: 'funabashi', name: '船橋', country: '日本', prefecture: '千葉縣', type: 'domestic', latitude: 35.6947, longitude: 139.9825),
        Destination(id: 'matsudo', name: '松戶', country: '日本', prefecture: '千葉縣', type: 'domestic', latitude: 35.7875, longitude: 139.9019),
        Destination(id: 'ichikawa', name: '市川', country: '日本', prefecture: '千葉縣', type: 'domestic', latitude: 35.7222, longitude: 139.9306),
        Destination(id: 'kashiwa', name: '柏', country: '日本', prefecture: '千葉縣', type: 'domestic', latitude: 35.8647, longitude: 139.9697),
      ],
      '東京都': [
        Destination(id: 'tokyo', name: '東京', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.6762, longitude: 139.6503),
        Destination(id: 'shibuya', name: '澀谷', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.6580, longitude: 139.7016),
        Destination(id: 'shinjuku', name: '新宿', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.6896, longitude: 139.6917),
        Destination(id: 'harajuku', name: '原宿', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.6702, longitude: 139.7026),
        Destination(id: 'asakusa', name: '淺草', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.7148, longitude: 139.7967),
        Destination(id: 'ginza', name: '銀座', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.6719, longitude: 139.7658),
        Destination(id: 'roppongi', name: '六本木', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.6627, longitude: 139.7314),
        Destination(id: 'akihabara', name: '秋葉原', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.7022, longitude: 139.7744),
        Destination(id: 'ueno', name: '上野', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.7139, longitude: 139.7767),
        Destination(id: 'ikebukuro', name: '池袋', country: '日本', prefecture: '東京都', type: 'domestic', latitude: 35.7289, longitude: 139.7106),
      ],
      '神奈川縣': [
        Destination(id: 'yokohama', name: '橫濱', country: '日本', prefecture: '神奈川縣', type: 'domestic', latitude: 35.4437, longitude: 139.6380),
        Destination(id: 'kamakura', name: '鎌倉', country: '日本', prefecture: '神奈川縣', type: 'domestic', latitude: 35.3191, longitude: 139.5466),
        Destination(id: 'hakone', name: '箱根', country: '日本', prefecture: '神奈川縣', type: 'domestic', latitude: 35.2323, longitude: 139.1070),
        Destination(id: 'kawasaki', name: '川崎', country: '日本', prefecture: '神奈川縣', type: 'domestic', latitude: 35.5308, longitude: 139.7028),
        Destination(id: 'fujisawa', name: '藤澤', country: '日本', prefecture: '神奈川縣', type: 'domestic', latitude: 35.3389, longitude: 139.4889),
      ],
      '新潟縣': [
        Destination(id: 'niigata', name: '新潟', country: '日本', prefecture: '新潟縣', type: 'domestic', latitude: 37.9161, longitude: 139.0364),
        Destination(id: 'nagaoka', name: '長岡', country: '日本', prefecture: '新潟縣', type: 'domestic', latitude: 37.4486, longitude: 138.8511),
        Destination(id: 'joetsu', name: '上越', country: '日本', prefecture: '新潟縣', type: 'domestic', latitude: 37.1467, longitude: 138.2361),
        Destination(id: 'sanjo', name: '三條', country: '日本', prefecture: '新潟縣', type: 'domestic', latitude: 37.6342, longitude: 138.9556),
        Destination(id: 'kashiwazaki', name: '柏崎', country: '日本', prefecture: '新潟縣', type: 'domestic', latitude: 37.3678, longitude: 138.5556),
      ],
      '富山縣': [
        Destination(id: 'toyama', name: '富山', country: '日本', prefecture: '富山縣', type: 'domestic', latitude: 36.6953, longitude: 137.2114),
        Destination(id: 'takaoka', name: '高岡', country: '日本', prefecture: '富山縣', type: 'domestic', latitude: 36.7533, longitude: 137.0164),
        Destination(id: 'uozu', name: '魚津', country: '日本', prefecture: '富山縣', type: 'domestic', latitude: 36.8181, longitude: 137.4086),
        Destination(id: 'himi', name: '冰見', country: '日本', prefecture: '富山縣', type: 'domestic', latitude: 36.8556, longitude: 136.9889),
        Destination(id: 'kurobe', name: '黑部', country: '日本', prefecture: '富山縣', type: 'domestic', latitude: 36.8722, longitude: 137.4556),
      ],
      '石川縣': [
        Destination(id: 'kanazawa', name: '金澤', country: '日本', prefecture: '石川縣', type: 'domestic', latitude: 36.5619, longitude: 136.6562),
        Destination(id: 'komatsu', name: '小松', country: '日本', prefecture: '石川縣', type: 'domestic', latitude: 36.4086, longitude: 136.4497),
        Destination(id: 'wajima', name: '輪島', country: '日本', prefecture: '石川縣', type: 'domestic', latitude: 37.3889, longitude: 136.8972),
        Destination(id: 'suzu', name: '珠洲', country: '日本', prefecture: '石川縣', type: 'domestic', latitude: 37.4431, longitude: 137.2597),
        Destination(id: 'nanao', name: '七尾', country: '日本', prefecture: '石川縣', type: 'domestic', latitude: 37.0444, longitude: 136.9656),
      ],
      '福井縣': [
        Destination(id: 'fukui', name: '福井', country: '日本', prefecture: '福井縣', type: 'domestic', latitude: 36.0642, longitude: 136.2197),
        Destination(id: 'tsuruga', name: '敦賀', country: '日本', prefecture: '福井縣', type: 'domestic', latitude: 35.6444, longitude: 136.0656),
        Destination(id: 'obama', name: '小濱', country: '日本', prefecture: '福井縣', type: 'domestic', latitude: 35.4953, longitude: 135.7469),
        Destination(id: 'ono', name: '大野', country: '日本', prefecture: '福井縣', type: 'domestic', latitude: 35.9844, longitude: 136.4856),
        Destination(id: 'katsuyama', name: '勝山', country: '日本', prefecture: '福井縣', type: 'domestic', latitude: 36.0608, longitude: 136.5019),
      ],
      '山梨縣': [
        Destination(id: 'kofu', name: '甲府', country: '日本', prefecture: '山梨縣', type: 'domestic', latitude: 35.6639, longitude: 138.5683),
        Destination(id: 'fuji', name: '富士吉田', country: '日本', prefecture: '山梨縣', type: 'domestic', latitude: 35.4886, longitude: 138.8019),
        Destination(id: 'tsuru', name: '都留', country: '日本', prefecture: '山梨縣', type: 'domestic', latitude: 35.5547, longitude: 138.9056),
        Destination(id: 'yamanashi', name: '山梨', country: '日本', prefecture: '山梨縣', type: 'domestic', latitude: 35.6914, longitude: 138.6806),
        Destination(id: 'otsuki', name: '大月', country: '日本', prefecture: '山梨縣', type: 'domestic', latitude: 35.6106, longitude: 138.9444),
      ],
      '長野縣': [
        Destination(id: 'nagano', name: '長野', country: '日本', prefecture: '長野縣', type: 'domestic', latitude: 36.6513, longitude: 138.1811),
        Destination(id: 'matsumoto', name: '松本', country: '日本', prefecture: '長野縣', type: 'domestic', latitude: 36.2381, longitude: 137.9722),
        Destination(id: 'ueda', name: '上田', country: '日本', prefecture: '長野縣', type: 'domestic', latitude: 36.4014, longitude: 138.2486),
        Destination(id: 'iida', name: '飯田', country: '日本', prefecture: '長野縣', type: 'domestic', latitude: 35.5139, longitude: 137.8197),
        Destination(id: 'suwa', name: '諏訪', country: '日本', prefecture: '長野縣', type: 'domestic', latitude: 36.0408, longitude: 138.1144),
      ],
      '岐阜縣': [
        Destination(id: 'gifu', name: '岐阜', country: '日本', prefecture: '岐阜縣', type: 'domestic', latitude: 35.3911, longitude: 136.7222),
        Destination(id: 'ogaki', name: '大垣', country: '日本', prefecture: '岐阜縣', type: 'domestic', latitude: 35.3669, longitude: 136.6181),
        Destination(id: 'takayama', name: '高山', country: '日本', prefecture: '岐阜縣', type: 'domestic', latitude: 36.1458, longitude: 137.2511),
        Destination(id: 'tajimi', name: '多治見', country: '日本', prefecture: '岐阜縣', type: 'domestic', latitude: 35.3311, longitude: 137.1244),
        Destination(id: 'kani', name: '可兒', country: '日本', prefecture: '岐阜縣', type: 'domestic', latitude: 35.4264, longitude: 137.0581),
      ],
      '靜岡縣': [
        Destination(id: 'shizuoka', name: '靜岡', country: '日本', prefecture: '靜岡縣', type: 'domestic', latitude: 34.9756, longitude: 138.3828),
        Destination(id: 'hamamatsu', name: '濱松', country: '日本', prefecture: '靜岡縣', type: 'domestic', latitude: 34.7108, longitude: 137.7261),
        Destination(id: 'numazu', name: '沼津', country: '日本', prefecture: '靜岡縣', type: 'domestic', latitude: 35.0956, longitude: 138.8636),
        Destination(id: 'fuji', name: '富士', country: '日本', prefecture: '靜岡縣', type: 'domestic', latitude: 35.1614, longitude: 138.6767),
        Destination(id: 'atami', name: '熱海', country: '日本', prefecture: '靜岡縣', type: 'domestic', latitude: 35.0953, longitude: 139.0731),
      ],
      '愛知縣': [
        Destination(id: 'nagoya', name: '名古屋', country: '日本', prefecture: '愛知縣', type: 'domestic', latitude: 35.1815, longitude: 136.9066),
        Destination(id: 'toyota', name: '豐田', country: '日本', prefecture: '愛知縣', type: 'domestic', latitude: 35.0831, longitude: 137.1544),
        Destination(id: 'okazaki', name: '岡崎', country: '日本', prefecture: '愛知縣', type: 'domestic', latitude: 34.9553, longitude: 137.1744),
        Destination(id: 'ichinomiya', name: '一宮', country: '日本', prefecture: '愛知縣', type: 'domestic', latitude: 35.3031, longitude: 136.8006),
        Destination(id: 'kasugai', name: '春日井', country: '日本', prefecture: '愛知縣', type: 'domestic', latitude: 35.2478, longitude: 136.9719),
      ],
      '三重縣': [
        Destination(id: 'tsu', name: '津', country: '日本', prefecture: '三重縣', type: 'domestic', latitude: 34.7303, longitude: 136.5086),
        Destination(id: 'yokkaichi', name: '四日市', country: '日本', prefecture: '三重縣', type: 'domestic', latitude: 34.9656, longitude: 136.6250),
        Destination(id: 'ise', name: '伊勢', country: '日本', prefecture: '三重縣', type: 'domestic', latitude: 34.4889, longitude: 136.7081),
        Destination(id: 'matsusaka', name: '松阪', country: '日本', prefecture: '三重縣', type: 'domestic', latitude: 34.5781, longitude: 136.5253),
        Destination(id: 'kuwana', name: '桑名', country: '日本', prefecture: '三重縣', type: 'domestic', latitude: 35.0622, longitude: 136.6844),
      ],
      '滋賀縣': [
        Destination(id: 'otsu', name: '大津', country: '日本', prefecture: '滋賀縣', type: 'domestic', latitude: 35.0044, longitude: 135.8686),
        Destination(id: 'hikone', name: '彥根', country: '日本', prefecture: '滋賀縣', type: 'domestic', latitude: 35.2744, longitude: 136.2586),
        Destination(id: 'kusatsu', name: '草津', country: '日本', prefecture: '滋賀縣', type: 'domestic', latitude: 35.0178, longitude: 135.9597),
        Destination(id: 'moriyama', name: '守山', country: '日本', prefecture: '滋賀縣', type: 'domestic', latitude: 35.0289, longitude: 135.9722),
        Destination(id: 'ritto', name: '栗東', country: '日本', prefecture: '滋賀縣', type: 'domestic', latitude: 35.0181, longitude: 135.9997),
      ],
      '京都府': [
        Destination(id: 'kyoto', name: '京都', country: '日本', prefecture: '京都府', type: 'domestic', latitude: 35.0116, longitude: 135.7681),
        Destination(id: 'arashiyama', name: '嵐山', country: '日本', prefecture: '京都府', type: 'domestic', latitude: 35.0175, longitude: 135.6761),
        Destination(id: 'gion', name: '祇園', country: '日本', prefecture: '京都府', type: 'domestic', latitude: 35.0037, longitude: 135.7751),
        Destination(id: 'fushimi', name: '伏見', country: '日本', prefecture: '京都府', type: 'domestic', latitude: 34.9378, longitude: 135.7581),
        Destination(id: 'uji', name: '宇治', country: '日本', prefecture: '京都府', type: 'domestic', latitude: 34.8842, longitude: 135.7997),
      ],
      '大阪府': [
        Destination(id: 'osaka', name: '大阪', country: '日本', prefecture: '大阪府', type: 'domestic', latitude: 34.6937, longitude: 135.5023),
        Destination(id: 'namba', name: '難波', country: '日本', prefecture: '大阪府', type: 'domestic', latitude: 34.6659, longitude: 135.5018),
        Destination(id: 'umeda', name: '梅田', country: '日本', prefecture: '大阪府', type: 'domestic', latitude: 34.7024, longitude: 135.4959),
        Destination(id: 'tennoji', name: '天王寺', country: '日本', prefecture: '大阪府', type: 'domestic', latitude: 34.6452, longitude: 135.5066),
        Destination(id: 'sakai', name: '堺', country: '日本', prefecture: '大阪府', type: 'domestic', latitude: 34.5733, longitude: 135.4828),
      ],
      '兵庫縣': [
        Destination(id: 'kobe', name: '神戶', country: '日本', prefecture: '兵庫縣', type: 'domestic', latitude: 34.6901, longitude: 135.1956),
        Destination(id: 'himeji', name: '姬路', country: '日本', prefecture: '兵庫縣', type: 'domestic', latitude: 34.8161, longitude: 134.6856),
        Destination(id: 'nishinomiya', name: '西宮', country: '日本', prefecture: '兵庫縣', type: 'domestic', latitude: 34.7381, longitude: 135.3411),
        Destination(id: 'amagasaki', name: '尼崎', country: '日本', prefecture: '兵庫縣', type: 'domestic', latitude: 34.7331, longitude: 135.4064),
        Destination(id: 'akashi', name: '明石', country: '日本', prefecture: '兵庫縣', type: 'domestic', latitude: 34.6431, longitude: 134.9981),
      ],
      '奈良縣': [
        Destination(id: 'nara', name: '奈良', country: '日本', prefecture: '奈良縣', type: 'domestic', latitude: 34.6851, longitude: 135.8048),
        Destination(id: 'kashihara', name: '橿原', country: '日本', prefecture: '奈良縣', type: 'domestic', latitude: 34.5097, longitude: 135.7928),
        Destination(id: 'yamatotakada', name: '大和高田', country: '日本', prefecture: '奈良縣', type: 'domestic', latitude: 34.5156, longitude: 135.7378),
        Destination(id: 'yamatokoriyama', name: '大和郡山', country: '日本', prefecture: '奈良縣', type: 'domestic', latitude: 34.6489, longitude: 135.7831),
        Destination(id: 'tenri', name: '天理', country: '日本', prefecture: '奈良縣', type: 'domestic', latitude: 34.5964, longitude: 135.8378),
      ],
      '和歌山縣': [
        Destination(id: 'wakayama', name: '和歌山', country: '日本', prefecture: '和歌山縣', type: 'domestic', latitude: 34.2261, longitude: 135.1675),
        Destination(id: 'tanabe', name: '田邊', country: '日本', prefecture: '和歌山縣', type: 'domestic', latitude: 33.7306, longitude: 135.3756),
        Destination(id: 'hashimoto', name: '橋本', country: '日本', prefecture: '和歌山縣', type: 'domestic', latitude: 34.3156, longitude: 135.6031),
        Destination(id: 'arida', name: '有田', country: '日本', prefecture: '和歌山縣', type: 'domestic', latitude: 34.0831, longitude: 135.1281),
        Destination(id: 'gobo', name: '御坊', country: '日本', prefecture: '和歌山縣', type: 'domestic', latitude: 33.8917, longitude: 135.1631),
      ],
      '鳥取縣': [
        Destination(id: 'tottori', name: '鳥取', country: '日本', prefecture: '鳥取縣', type: 'domestic', latitude: 35.5036, longitude: 134.2378),
        Destination(id: 'yonago', name: '米子', country: '日本', prefecture: '鳥取縣', type: 'domestic', latitude: 35.4328, longitude: 133.3306),
        Destination(id: 'kurayoshi', name: '倉吉', country: '日本', prefecture: '鳥取縣', type: 'domestic', latitude: 35.4297, longitude: 133.8256),
        Destination(id: 'sakaiminato', name: '境港', country: '日本', prefecture: '鳥取縣', type: 'domestic', latitude: 35.5431, longitude: 133.2331),
      ],
      '島根縣': [
        Destination(id: 'matsue', name: '松江', country: '日本', prefecture: '島根縣', type: 'domestic', latitude: 35.4722, longitude: 133.0506),
        Destination(id: 'hamada', name: '濱田', country: '日本', prefecture: '島根縣', type: 'domestic', latitude: 34.8978, longitude: 132.0806),
        Destination(id: 'izumo', name: '出雲', country: '日本', prefecture: '島根縣', type: 'domestic', latitude: 35.3667, longitude: 132.7544),
        Destination(id: 'masuda', name: '益田', country: '日本', prefecture: '島根縣', type: 'domestic', latitude: 34.6667, longitude: 131.8456),
        Destination(id: 'oda', name: '大田', country: '日本', prefecture: '島根縣', type: 'domestic', latitude: 35.1944, longitude: 132.5019),
      ],
      '岡山縣': [
        Destination(id: 'okayama', name: '岡山', country: '日本', prefecture: '岡山縣', type: 'domestic', latitude: 34.6617, longitude: 133.9353),
        Destination(id: 'kurashiki', name: '倉敷', country: '日本', prefecture: '岡山縣', type: 'domestic', latitude: 34.5839, longitude: 133.7722),
        Destination(id: 'tsuyama', name: '津山', country: '日本', prefecture: '岡山縣', type: 'domestic', latitude: 35.0644, longitude: 134.0044),
        Destination(id: 'tamano', name: '玉野', country: '日本', prefecture: '岡山縣', type: 'domestic', latitude: 34.4906, longitude: 133.9456),
        Destination(id: 'kasaoka', name: '笠岡', country: '日本', prefecture: '岡山縣', type: 'domestic', latitude: 34.5047, longitude: 133.5081),
      ],
      '廣島縣': [
        Destination(id: 'hiroshima', name: '廣島', country: '日本', prefecture: '廣島縣', type: 'domestic', latitude: 34.3853, longitude: 132.4553),
        Destination(id: 'fukuyama', name: '福山', country: '日本', prefecture: '廣島縣', type: 'domestic', latitude: 34.4856, longitude: 133.3622),
        Destination(id: 'kure', name: '吳', country: '日本', prefecture: '廣島縣', type: 'domestic', latitude: 34.2497, longitude: 132.5656),
        Destination(id: 'onomichi', name: '尾道', country: '日本', prefecture: '廣島縣', type: 'domestic', latitude: 34.4097, longitude: 133.2044),
        Destination(id: 'mihara', name: '三原', country: '日本', prefecture: '廣島縣', type: 'domestic', latitude: 34.3978, longitude: 133.0831),
      ],
      '山口縣': [
        Destination(id: 'yamaguchi', name: '山口', country: '日本', prefecture: '山口縣', type: 'domestic', latitude: 34.1856, longitude: 131.4706),
        Destination(id: 'shimonoseki', name: '下關', country: '日本', prefecture: '山口縣', type: 'domestic', latitude: 33.9578, longitude: 130.9406),
        Destination(id: 'ube', name: '宇部', country: '日本', prefecture: '山口縣', type: 'domestic', latitude: 33.9461, longitude: 131.2481),
        Destination(id: 'iwakuni', name: '岩國', country: '日本', prefecture: '山口縣', type: 'domestic', latitude: 34.1644, longitude: 132.2197),
        Destination(id: 'tokuyama', name: '德山', country: '日本', prefecture: '山口縣', type: 'domestic', latitude: 34.0556, longitude: 131.7931),
      ],
      '德島縣': [
        Destination(id: 'tokushima', name: '德島', country: '日本', prefecture: '德島縣', type: 'domestic', latitude: 34.0658, longitude: 134.5594),
        Destination(id: 'naruto', name: '鳴門', country: '日本', prefecture: '德島縣', type: 'domestic', latitude: 34.1756, longitude: 134.6097),
        Destination(id: 'komatsushima', name: '小松島', country: '日本', prefecture: '德島縣', type: 'domestic', latitude: 34.0044, longitude: 134.5931),
        Destination(id: 'anan', name: '阿南', country: '日本', prefecture: '德島縣', type: 'domestic', latitude: 33.9178, longitude: 134.6581),
        Destination(id: 'yoshinogawa', name: '吉野川', country: '日本', prefecture: '德島縣', type: 'domestic', latitude: 34.0681, longitude: 134.3456),
      ],
      '香川縣': [
        Destination(id: 'takamatsu', name: '高松', country: '日本', prefecture: '香川縣', type: 'domestic', latitude: 34.3403, longitude: 134.0431),
        Destination(id: 'marugame', name: '丸龜', country: '日本', prefecture: '香川縣', type: 'domestic', latitude: 34.2897, longitude: 133.7981),
        Destination(id: 'sakaide', name: '坂出', country: '日本', prefecture: '香川縣', type: 'domestic', latitude: 34.3156, longitude: 133.8656),
        Destination(id: 'zentsuji', name: '善通寺', country: '日本', prefecture: '香川縣', type: 'domestic', latitude: 34.2281, longitude: 133.7831),
        Destination(id: 'kanonji', name: '觀音寺', country: '日本', prefecture: '香川縣', type: 'domestic', latitude: 34.1281, longitude: 133.6531),
      ],
      '愛媛縣': [
        Destination(id: 'matsuyama', name: '松山', country: '日本', prefecture: '愛媛縣', type: 'domestic', latitude: 33.8419, longitude: 132.7656),
        Destination(id: 'imabari', name: '今治', country: '日本', prefecture: '愛媛縣', type: 'domestic', latitude: 34.0667, longitude: 132.9972),
        Destination(id: 'uwajima', name: '宇和島', country: '日本', prefecture: '愛媛縣', type: 'domestic', latitude: 33.2231, longitude: 132.5606),
        Destination(id: 'yawatahama', name: '八幡濱', country: '日本', prefecture: '愛媛縣', type: 'domestic', latitude: 33.4631, longitude: 132.4206),
        Destination(id: 'niihama', name: '新居濱', country: '日本', prefecture: '愛媛縣', type: 'domestic', latitude: 33.9511, longitude: 133.9506),
        Destination(id: 'saijo', name: '西條', country: '日本', prefecture: '愛媛縣', type: 'domestic', latitude: 33.9203, longitude: 133.1814),
      ],
      '高知縣': [
        Destination(id: 'kochi', name: '高知', country: '日本', prefecture: '高知縣', type: 'domestic', latitude: 33.5597, longitude: 133.5311),
        Destination(id: 'nankoku', name: '南國', country: '日本', prefecture: '高知縣', type: 'domestic', latitude: 33.5756, longitude: 133.6428),
        Destination(id: 'shimanto', name: '四萬十', country: '日本', prefecture: '高知縣', type: 'domestic', latitude: 32.9828, longitude: 132.9306),
        Destination(id: 'aki', name: '安藝', country: '日本', prefecture: '高知縣', type: 'domestic', latitude: 33.5006, longitude: 133.9089),
        Destination(id: 'susaki', name: '須崎', country: '日本', prefecture: '高知縣', type: 'domestic', latitude: 33.4031, longitude: 133.2781),
      ],
      '福岡縣': [
        Destination(id: 'fukuoka', name: '福岡', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.5904, longitude: 130.4017),
        Destination(id: 'kitakyushu', name: '北九州', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.8839, longitude: 130.8750),
        Destination(id: 'kurume', name: '久留米', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.3197, longitude: 130.5089),
        Destination(id: 'omuta', name: '大牟田', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.0306, longitude: 130.4456),
        Destination(id: 'iizuka', name: '飯塚', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.6456, longitude: 130.6856),
        Destination(id: 'tagawa', name: '田川', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.6381, longitude: 130.8056),
        Destination(id: 'yanagawa', name: '柳川', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.1622, longitude: 130.4056),
        Destination(id: 'yame', name: '八女', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.2111, longitude: 130.5556),
        Destination(id: 'chikugo', name: '筑後', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.2139, longitude: 130.5028),
        Destination(id: 'okawa', name: '大川', country: '日本', prefecture: '福岡縣', type: 'domestic', latitude: 33.2081, longitude: 130.3856),
      ],
      '佐賀縣': [
        Destination(id: 'saga', name: '佐賀', country: '日本', prefecture: '佐賀縣', type: 'domestic', latitude: 33.2494, longitude: 130.2989),
        Destination(id: 'karatsu', name: '唐津', country: '日本', prefecture: '佐賀縣', type: 'domestic', latitude: 33.4497, longitude: 129.9689),
        Destination(id: 'tosu', name: '鳥栖', country: '日本', prefecture: '佐賀縣', type: 'domestic', latitude: 33.3778, longitude: 130.5056),
        Destination(id: 'imari', name: '伊萬里', country: '日本', prefecture: '佐賀縣', type: 'domestic', latitude: 33.2656, longitude: 129.8789),
        Destination(id: 'takeo', name: '武雄', country: '日本', prefecture: '佐賀縣', type: 'domestic', latitude: 33.1931, longitude: 129.9956),
      ],
      '長崎縣': [
        Destination(id: 'nagasaki', name: '長崎', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 32.7503, longitude: 129.8781),
        Destination(id: 'sasebo', name: '佐世保', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 33.1597, longitude: 129.7233),
        Destination(id: 'isahaya', name: '諫早', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 32.8431, longitude: 130.0506),
        Destination(id: 'omura', name: '大村', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 32.9000, longitude: 129.9556),
        Destination(id: 'hirado', name: '平戶', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 33.3697, longitude: 129.5531),
        Destination(id: 'matsuura', name: '松浦', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 33.3411, longitude: 129.7081),
        Destination(id: 'tsushima', name: '對馬', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 34.2044, longitude: 129.2889),
        Destination(id: 'iki', name: '壹岐', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 33.7489, longitude: 129.6856),
        Destination(id: 'goto', name: '五島', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 32.6931, longitude: 128.8411),
        Destination(id: 'saikai', name: '西海', country: '日本', prefecture: '長崎縣', type: 'domestic', latitude: 32.9331, longitude: 129.5856),
      ],
      '熊本縣': [
        Destination(id: 'kumamoto', name: '熊本', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.8031, longitude: 130.7058),
        Destination(id: 'yatsushiro', name: '八代', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.5056, longitude: 130.6056),
        Destination(id: 'arao', name: '荒尾', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.9889, longitude: 130.4306),
        Destination(id: 'minamata', name: '水俣', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.2106, longitude: 130.4006),
        Destination(id: 'tamana', name: '玉名', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.9281, longitude: 130.5606),
        Destination(id: 'yamaga', name: '山鹿', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 33.0156, longitude: 130.6906),
        Destination(id: 'kikuchi', name: '菊池', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.9781, longitude: 130.8181),
        Destination(id: 'uto', name: '宇土', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.6889, longitude: 130.6431),
        Destination(id: 'uki', name: '宇城', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.6156, longitude: 130.6656),
        Destination(id: 'aso', name: '阿蘇', country: '日本', prefecture: '熊本縣', type: 'domestic', latitude: 32.9511, longitude: 131.1056),
      ],
      '大分縣': [
        Destination(id: 'oita', name: '大分', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 33.2381, longitude: 131.6125),
        Destination(id: 'beppu', name: '別府', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 33.2844, longitude: 131.4914),
        Destination(id: 'nakatsu', name: '中津', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 33.5981, longitude: 131.1881),
        Destination(id: 'hita', name: '日田', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 33.3225, longitude: 130.9406),
        Destination(id: 'saiki', name: '佐伯', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 32.9597, longitude: 131.9006),
        Destination(id: 'usuki', name: '臼杵', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 33.1256, longitude: 131.8056),
        Destination(id: 'tsukumi', name: '津久見', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 33.0656, longitude: 131.8656),
        Destination(id: 'taketa', name: '竹田', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 32.9731, longitude: 131.3956),
        Destination(id: 'bungoono', name: '豐後大野', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 32.9656, longitude: 131.6056),
        Destination(id: 'yufu', name: '由布', country: '日本', prefecture: '大分縣', type: 'domestic', latitude: 33.1806, longitude: 131.4306),
      ],
      '宮崎縣': [
        Destination(id: 'miyazaki', name: '宮崎', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 31.9077, longitude: 131.4202),
        Destination(id: 'miyakonojo', name: '都城', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 31.7281, longitude: 131.0656),
        Destination(id: 'nobeoka', name: '延岡', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 32.5822, longitude: 131.6656),
        Destination(id: 'nichinan', name: '日南', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 31.5989, longitude: 131.3781),
        Destination(id: 'kobayashi', name: '小林', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 31.9981, longitude: 130.9756),
        Destination(id: 'hyuga', name: '日向', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 32.4214, longitude: 131.6256),
        Destination(id: 'kushima', name: '串間', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 31.4631, longitude: 131.2256),
        Destination(id: 'saito', name: '西都', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 32.1031, longitude: 131.3956),
        Destination(id: 'ebino', name: '蝦野', country: '日本', prefecture: '宮崎縣', type: 'domestic', latitude: 32.0356, longitude: 130.8106),
      ],
      '鹿兒島縣': [
        Destination(id: 'kagoshima', name: '鹿兒島', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 31.5966, longitude: 130.5581),
        Destination(id: 'kanoya', name: '鹿屋', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 31.3781, longitude: 130.8506),
        Destination(id: 'makurazaki', name: '枕崎', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 31.2731, longitude: 130.2981),
        Destination(id: 'akune', name: '阿久根', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 32.0156, longitude: 130.1956),
        Destination(id: 'izumi', name: '出水', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 32.0856, longitude: 130.3556),
        Destination(id: 'ibusuki', name: '指宿', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 31.2531, longitude: 130.6431),
        Destination(id: 'nishinoomote', name: '西之表', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 30.7356, longitude: 131.0006),
        Destination(id: 'tarumizu', name: '垂水', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 31.4906, longitude: 130.7006),
        Destination(id: 'satsumasendai', name: '薩摩川內', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 31.8156, longitude: 130.3056),
        Destination(id: 'hioki', name: '日置', country: '日本', prefecture: '鹿兒島縣', type: 'domestic', latitude: 31.6356, longitude: 130.3956),
      ],
      '沖繩縣': [
        Destination(id: 'naha', name: '那霸', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.2124, longitude: 127.6792),
        Destination(id: 'ginowan', name: '宜野灣', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.2806, longitude: 127.7806),
        Destination(id: 'ishigaki', name: '石垣', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 24.3389, longitude: 124.1556),
        Destination(id: 'urasoe', name: '浦添', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.2456, longitude: 127.7256),
        Destination(id: 'nago', name: '名護', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.5931, longitude: 127.9781),
        Destination(id: 'itoman', name: '糸滿', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.1231, longitude: 127.6656),
        Destination(id: 'okinawa', name: '沖繩', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.3356, longitude: 127.8056),
        Destination(id: 'tomigusuku', name: '豐見城', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.1631, longitude: 127.6681),
        Destination(id: 'uruma', name: '宇流麻', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 26.3731, longitude: 127.8506),
        Destination(id: 'miyakojima', name: '宮古島', country: '日本', prefecture: '沖繩縣', type: 'domestic', latitude: 24.8056, longitude: 125.2806),
      ],
    };
  }

  // 搜尋目的地
  static List<Destination> searchDestinations(String query) {
    final allDestinations = <Destination>[];
    
    // 先添加所有國內地點
    getDomesticDestinations().values.forEach((destinations) {
      allDestinations.addAll(destinations);
    });
    
    // 再添加所有國外地點
    getInternationalDestinations().values.forEach((destinations) {
      allDestinations.addAll(destinations);
    });
    
    // 創建一個 Map 來存儲去重後的目的地，熱門地點會覆蓋基本地點
    final uniqueDestinations = <String, Destination>{};
    for (final destination in allDestinations) {
      uniqueDestinations[destination.id] = destination;
    }
    
    // 添加所有熱門地點（國內和國外），這些會覆蓋基本地點資訊
    final popularDestinations = <Destination>[];
    popularDestinations.addAll(getPopularDomesticDestinations());
    popularDestinations.addAll(getPopularInternationalDestinations());
    
    for (final destination in popularDestinations) {
      uniqueDestinations[destination.id] = destination; // 熱門地點覆蓋基本地點
    }
    
    // 搜尋
    if (query.isEmpty) {
      return uniqueDestinations.values.toList();
    }
    
    return uniqueDestinations.values
        .where((destination) =>
            destination.name.toLowerCase().contains(query.toLowerCase()) ||
            destination.country.toLowerCase().contains(query.toLowerCase()) ||
            (destination.prefecture?.toLowerCase().contains(query.toLowerCase()) ?? false))
        .toList();
  }
}
